[site]
title = "Yanyan Huang · 黄岩岩"
description = "Personal website of Yanyan Huang"
favicon = "/favicon.ico"
last_updated = "November 28, 2025"

[author]
name = "Yanyan Huang"
title = "PhD Student"
institution = "The University of Hong Kong"
avatar = "/bio.png"

[social]
# Contact information (leave blank or delete to hide)

email = "yanyanh@connect.hku.hk"
location = "Hong Kong"
location_url = "https://www.hku.hk/"
location_details = [
  "School of Computing and Data Science,",
  "The University of Hong Kong, Hong Kong"
]
google_scholar = "https://scholar.google.com/citations?user=6mQ6b1EAAAAJ"
orcid = ""
github = "https://github.com/yanyanhuang"
linkedin = "https://linkedin.com/in/yyhuang8"
kaggle = "https://www.kaggle.com/rock139"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"
